bcc: null
cc: null
enabled: false
language: orderLanguage
name: 'Order Received'
plainTextTemplatePath: null
recipientType: customer
replyTo: null
subject: 'We''ve got it! Thanks for your order!'
templatePath: _special/emails/received
to: null
