fieldLayouts:
  f35f48a2-5520-4076-bee1-e1f5134c3145:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5c41788c-6748-4368-aa7b-69c7461225e6
            warning: null
            width: 100
          -
            fieldUid: 9b41a7f2-dc44-4ede-8931-b8f5895093f7 # Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5451970-4f1c-4076-83a1-74a60170fb01
            warning: null
            width: 100
          -
            fieldUid: ba0c0b5b-813d-4075-acec-9700550b80ae # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c5e0c74-1dd4-429a-85fd-7377edb2f7d4
            warning: null
            width: 100
        name: Content
        uid: 184aa23a-08e9-4f4e-933a-200f44850885
fs: $FS_HANDLE
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
