columnSuffix: null
contentColumnType: string
fieldGroup: 6aa1ad27-db4b-4af9-8658-d93eff3d4512 # Common
handle: footerNav
instructions: 'Use the available block types to build the site’s global footer navigation. Each block type represents a column.'
name: 'Footer Nav'
searchable: false
settings:
  contentTable: '{{%matrixcontent_footernav}}'
  maxBlocks: 4
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
