fieldLayouts:
  99b69fc3-3792-4187-9bbd-0bfd84dc876d:
    tabs:
      -
        elements:
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: 'Enter copyright text to be displayed in every page footer. (Will automatically be preceded with copyright symbol and year.)'
            label: Copyright
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ac99d8c-ee7e-47bf-b8cb-e758986721d2
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: 'Enter a description of the active site’s language to be displayed in the footer. (Not currently implemented.)'
            label: 'Language Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58bec81a-7cea-46d6-bbc0-f07dd6f275cf
            warning: null
            width: 100
        name: Content
        uid: efced2de-a26d-4991-b642-88a3f3a0c4ad
      -
        elements:
          -
            fieldUid: b9cb6112-ebae-420b-bae9-a54c387419f6 # Footer Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f8df64a-3f2d-4faf-86c4-55dffdf60514
            warning: null
            width: 100
        name: Nav
        uid: 9d3cbf46-c7b3-411a-8cba-6cd49efb3a77
handle: footer
name: Footer
sortOrder: 3
