description: null
handle: storeManagers
name: 'Store Managers'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-commerce
  - accessplugin-freeform
  - accessplugin-seomatic
  - accesssitewhensystemisoff
  - administrateusers
  - 'assignusergroup:229f9f29-ca35-402b-973b-8fb12d4d68ec' # Customers
  - 'assignusergroup:89d30b8d-7f71-4571-bfd3-572a14dc6538' # VIP Customers
  - 'assignusergroup:8b2b60fd-6045-4696-b08e-6c601ac1245f' # Content Managers
  - 'assignusergroup:e9aeb271-1582-40b5-b7c8-dc4bed8d7bfe' # Store Managers
  - assignuserpermissions
  - commerce-capturepayment
  - commerce-deleteorders
  - commerce-editorders
  - commerce-manageorders
  - 'commerce-editproducttype:03450688-d7c8-4bc8-bd13-fff95a960e2b' # Bike
  - commerce-managepromotions
  - commerce-manageshipping
  - commerce-managestoresettings
  - commerce-managesubscriptions
  - commerce-managetaxes
  - commerce-refundpayment
  - 'createentries:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'createentries:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'createentries:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'createentries:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'createentries:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'createentries:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'createentries:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'createentries:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'deleteentries:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'deleteentries:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'deleteentries:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'deleteentries:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'deleteentries:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'deleteentries:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'deleteentries:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'deleteentries:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'deletepeerentries:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'deletepeerentries:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'deletepeerentries:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'deletepeerentries:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'deletepeerentries:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'deletepeerentries:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'deletepeerentries:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'deletepeerentries:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'deletepeerentrydrafts:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'deletepeerentrydrafts:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'deletepeerentrydrafts:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'deletepeerentrydrafts:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'deletepeerentrydrafts:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'deletepeerentrydrafts:384841aa-9783-4efd-a81f-0f4aa159ab33' # Bikes
  - 'deletepeerentrydrafts:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'deletepeerentrydrafts:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'deletepeerentrydrafts:60203e95-0439-4fdf-a99f-b85c845abc12' # Homepage
  - 'deletepeerentrydrafts:706870b0-b231-4710-947c-e3e6bd5c7062' # Articles Landing
  - 'deletepeerentrydrafts:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'deletepeerentrydrafts:9b9e7f64-d3ac-4cd8-9ac6-2dad92ba68f1' # Contact
  - 'deletepeerentrydrafts:a47082e1-a4c7-48c4-b08e-e84d5dae0956' # Search
  - 'deletepeerentrydrafts:d64cd626-dade-430d-98d1-9b9be69592c0' # Services
  - deleteusers
  - 'editglobalset:2a2f0ac5-fb77-412b-8259-4445f3520dae' # Shop
  - 'editglobalset:63ae8822-3b4e-4a3d-b902-eba33875c230' # Footer
  - 'editglobalset:ba795823-7853-4c7d-8337-136027e1e738' # Bikes
  - editusers
  - freeform-access-quick-export
  - freeform-dashboardaccess
  - freeform-fieldsaccess
  - freeform-fieldsmanage
  - freeform-formsaccess
  - freeform-formscreate
  - freeform-formsdelete
  - freeform-formsmanage
  - 'freeform-formsmanage:1'
  - 'freeform-formsmanage:2'
  - 'freeform-formsmanage:3'
  - freeform-formsmanageindividual
  - freeform-notificationsaccess
  - freeform-notificationsmanage
  - freeform-pro-exportprofilesaccess
  - freeform-pro-exportprofilesmanage
  - freeform-resources
  - freeform-settingsaccess
  - freeform-submissionsaccess
  - freeform-submissionsmanage
  - 'freeform-submissionsmanage:1'
  - 'freeform-submissionsmanage:2'
  - 'freeform-submissionsmanage:3'
  - freeform-submissionsmanageindividual
  - freeform-submissionsread
  - 'freeform-submissionsread:1'
  - 'freeform-submissionsread:2'
  - 'freeform-submissionsread:3'
  - freeform-submissionsreadindividual
  - impersonateusers
  - moderateusers
  - registerusers
  - 'viewassets:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'saveassets:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'deleteassets:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'replacefiles:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'editimages:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'viewpeerassets:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'savepeerassets:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'replacepeerfiles:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'deletepeerassets:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'editpeerimages:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'createfolders:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
  - 'viewcategories:aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57' # Bike Types
  - 'savecategories:aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57' # Bike Types
  - 'deletecategories:aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57' # Bike Types
  - 'viewpeercategorydrafts:aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57' # Bike Types
  - 'savepeercategorydrafts:aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57' # Bike Types
  - 'deletepeercategorydrafts:aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57' # Bike Types
  - 'viewcategories:5a97754b-a6d0-41f2-ba98-cf145d689df1' # Colors
  - 'savecategories:5a97754b-a6d0-41f2-ba98-cf145d689df1' # Colors
  - 'deletecategories:5a97754b-a6d0-41f2-ba98-cf145d689df1' # Colors
  - 'viewpeercategorydrafts:5a97754b-a6d0-41f2-ba98-cf145d689df1' # Colors
  - 'savepeercategorydrafts:5a97754b-a6d0-41f2-ba98-cf145d689df1' # Colors
  - 'deletepeercategorydrafts:5a97754b-a6d0-41f2-ba98-cf145d689df1' # Colors
  - 'viewcategories:dcef5c5f-2446-44fa-8898-1bc3daa2d2fd' # Equipment Types
  - 'savecategories:dcef5c5f-2446-44fa-8898-1bc3daa2d2fd' # Equipment Types
  - 'deletecategories:dcef5c5f-2446-44fa-8898-1bc3daa2d2fd' # Equipment Types
  - 'viewpeercategorydrafts:dcef5c5f-2446-44fa-8898-1bc3daa2d2fd' # Equipment Types
  - 'savepeercategorydrafts:dcef5c5f-2446-44fa-8898-1bc3daa2d2fd' # Equipment Types
  - 'deletepeercategorydrafts:dcef5c5f-2446-44fa-8898-1bc3daa2d2fd' # Equipment Types
  - 'viewcategories:562224df-c083-4f48-b0b3-7bdcb9bd8df9' # Material
  - 'savecategories:562224df-c083-4f48-b0b3-7bdcb9bd8df9' # Material
  - 'deletecategories:562224df-c083-4f48-b0b3-7bdcb9bd8df9' # Material
  - 'viewpeercategorydrafts:562224df-c083-4f48-b0b3-7bdcb9bd8df9' # Material
  - 'savepeercategorydrafts:562224df-c083-4f48-b0b3-7bdcb9bd8df9' # Material
  - 'deletepeercategorydrafts:562224df-c083-4f48-b0b3-7bdcb9bd8df9' # Material
  - 'viewentries:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'saveentries:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'viewpeerentrydrafts:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'savepeerentrydrafts:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'viewpeerentries:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'savepeerentries:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
  - 'viewentries:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'saveentries:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'viewpeerentrydrafts:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'savepeerentrydrafts:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'viewpeerentries:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'savepeerentries:5075e975-0eb8-4e62-9ae7-9d8cd88348eb' # Emails
  - 'viewentries:9b9e7f64-d3ac-4cd8-9ac6-2dad92ba68f1' # Contact
  - 'saveentries:9b9e7f64-d3ac-4cd8-9ac6-2dad92ba68f1' # Contact
  - 'viewpeerentrydrafts:9b9e7f64-d3ac-4cd8-9ac6-2dad92ba68f1' # Contact
  - 'savepeerentrydrafts:9b9e7f64-d3ac-4cd8-9ac6-2dad92ba68f1' # Contact
  - 'viewentries:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'saveentries:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'viewpeerentrydrafts:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'savepeerentrydrafts:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'viewpeerentries:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'savepeerentries:0f952e73-17b8-408c-9c37-3f07a5d16a92' # Error Pages
  - 'viewentries:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'saveentries:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'viewpeerentrydrafts:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'savepeerentrydrafts:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'viewpeerentries:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'savepeerentries:220feec1-8cc9-4f3e-82da-73c748d0ae0b' # PDFs
  - 'viewentries:60203e95-0439-4fdf-a99f-b85c845abc12' # Homepage
  - 'saveentries:60203e95-0439-4fdf-a99f-b85c845abc12' # Homepage
  - 'viewpeerentrydrafts:60203e95-0439-4fdf-a99f-b85c845abc12' # Homepage
  - 'savepeerentrydrafts:60203e95-0439-4fdf-a99f-b85c845abc12' # Homepage
  - 'viewentries:a47082e1-a4c7-48c4-b08e-e84d5dae0956' # Search
  - 'saveentries:a47082e1-a4c7-48c4-b08e-e84d5dae0956' # Search
  - 'viewpeerentrydrafts:a47082e1-a4c7-48c4-b08e-e84d5dae0956' # Search
  - 'savepeerentrydrafts:a47082e1-a4c7-48c4-b08e-e84d5dae0956' # Search
  - 'viewentries:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'saveentries:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'viewpeerentrydrafts:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'savepeerentrydrafts:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'viewpeerentries:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'savepeerentries:32faa6bc-a330-408a-b37a-4e8bde606b43' # Reviews
  - 'viewentries:706870b0-b231-4710-947c-e3e6bd5c7062' # Articles Landing
  - 'saveentries:706870b0-b231-4710-947c-e3e6bd5c7062' # Articles Landing
  - 'viewpeerentrydrafts:706870b0-b231-4710-947c-e3e6bd5c7062' # Articles Landing
  - 'savepeerentrydrafts:706870b0-b231-4710-947c-e3e6bd5c7062' # Articles Landing
  - 'viewentries:d64cd626-dade-430d-98d1-9b9be69592c0' # Services
  - 'saveentries:d64cd626-dade-430d-98d1-9b9be69592c0' # Services
  - 'viewpeerentrydrafts:d64cd626-dade-430d-98d1-9b9be69592c0' # Services
  - 'savepeerentrydrafts:d64cd626-dade-430d-98d1-9b9be69592c0' # Services
  - 'viewentries:384841aa-9783-4efd-a81f-0f4aa159ab33' # Bikes
  - 'saveentries:384841aa-9783-4efd-a81f-0f4aa159ab33' # Bikes
  - 'viewpeerentrydrafts:384841aa-9783-4efd-a81f-0f4aa159ab33' # Bikes
  - 'savepeerentrydrafts:384841aa-9783-4efd-a81f-0f4aa159ab33' # Bikes
  - 'viewentries:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'saveentries:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'viewpeerentrydrafts:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'savepeerentrydrafts:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'viewpeerentries:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'savepeerentries:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
  - 'viewentries:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'saveentries:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'viewpeerentrydrafts:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'savepeerentrydrafts:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'viewpeerentries:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'savepeerentries:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
  - 'viewentries:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'saveentries:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'viewpeerentrydrafts:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'savepeerentrydrafts:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'viewpeerentries:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - 'savepeerentries:97a0491d-814e-4172-811d-51096a86e67d' # Plans
  - commerce-editsales
  - commerce-createsales
  - commerce-deletesales
  - commerce-editdiscounts
  - commerce-creatediscounts
  - commerce-deletediscounts
  - 'commerce-createproducts:03450688-d7c8-4bc8-bd13-fff95a960e2b' # Bike
  - 'commerce-deleteproducts:03450688-d7c8-4bc8-bd13-fff95a960e2b' # Bike
